package libcrypto

// Encryption result returned from a successful encryption
type EncryptionResult struct {
	// The encrypted data
	Data []byte
	// The key that was generated by the encryption
	Key []byte
}